language: java
services:
  - docker

before_install:
  - pip install awscli
  - curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
  - sudo mv /tmp/eksctl /usr/local/bin
  - eksctl version

deploy:
  provider: script
  script: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $DOCKER_ECR_REPO_URL && ./gradlew build dockerPush -x test -PdockerRepository=$DOCKER_ECR_REPO_URL/api-server
  on:
    branch: master