sudo: required
language: java
services:
  - docker

before_install:
  - pip install awscli

deploy:
  provider: script
  script: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $DOCKER_ECR_REPO_URL && ./gradlew build dockerPush -x test -PdockerRepository=$DOCKER_ECR_REPO_URL/api-server
  on:
    branch: master