language: java
services:
  - docker

env:
  global:
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
  - pip install awscli
  - curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
  - sudo mv /tmp/eksctl /usr/local/bin
  - curl https://sdk.cloud.google.com | bash > /dev/null
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components install kubectl
  - eksctl version

deploy:
  provider: script
  script: >
    aws ecr get-login-password --region us-east-1 |
    docker login --username AWS --password-stdin $DOCKER_ECR_REPO_URL &&
    ./gradlew build dockerPush -x test -PdockerRepository=$DOCKER_ECR_REPO_URL/api-server &&
    aws eks --region us-east-1 update-kubeconfig --name $EKS_CLUSTER &&
    kubectl scale deployment $DEPLOYMENT --replicas=0 &&
    kubectl scale deployment $DEPLOYMENT --replicas=1 &&
    echo deploy
  on:
    branch: master